stages:
  - build
  - deploy

variables:
  ECR_REPO_URI: $ECR_REPO_URI
  AWS_REGION: $AWS_REGION
  EC2_HOST: $EC2_HOST
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY

build:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  script:
    # Встановлення AWS CLI
    - apk add --no-cache python3 py3-pip
    - pip install awscli
    # Аутентифікація в ECR
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
    # Створення Docker-образу та відправка в репозиторій
    - docker build -t $ECR_REPO_URI .
    - docker push $ECR_REPO_URI

deploy:
  stage: deploy
  script:
    - echo "$SSH_PRIVATE_KEY" > private_key.pem
    - chmod 600 private_key.pem
    - ssh -i private_key.pem ec2-user@$EC2_HOST 'docker pull $ECR_REPO_URI && cd /path/to/docker-compose/directory && docker-compose up -d'
  only:
    - main
