name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ECR_URI }}:latest .
          docker push ${{ secrets.ECR_URI }}:latest

      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ECR_URI: ${{ secrets.ECR_URI }}
        run: |
          echo "$SSH_PRIVATE_KEY" > /tmp/private_key.pem
          chmod 600 /tmp/private_key.pem
          ssh -o StrictHostKeyChecking=no -i /tmp/private_key.pem ec2-user@35.173.203.244 << 'EOF'
            docker pull $ECR_URI:latest
            docker-compose -f /path/to/your/docker-compose.yml up -d
          EOF
